#!/usr/bin/env python3
"""
Compile state-specific Grade 4 math LaTeX books and collect PDFs.

This script:
  1. Discovers .tex files generated by generate_state_books.py in state_books/
  2. Compiles them concurrently with xelatex (2 passes for cross-refs)
  3. Copies final PDFs (date-stamped) into final_output/{book_type}/

When compiling multiple book types (--book-type all), ALL .tex files across
every book type are compiled in a single concurrent pool so the machine's
cores are fully utilised.

The .tex files must already exist under state_books/<state>/.
Use generate_state_books.py to create them first.

Usage examples:
    # Compile ALL book types for all 50 states (full concurrency)
    python3 scripts/compile_state_books.py --book-type all

    # Compile ALL all-in-one books for all 50 states
    python3 scripts/compile_state_books.py --book-type all_in_one

    # Compile ALL book types for one state (concurrent across types)
    python3 scripts/compile_state_books.py --book-type all --states texas

    # Specific states only
    python3 scripts/compile_state_books.py --book-type all_in_one --states texas,florida

    # Control concurrent compilations (or set MAX_WORKERS in .env)
    python3 scripts/compile_state_books.py --book-type all_in_one --jobs 4

    # More xelatex passes (or set XELATEX_PASSES in .env)
    python3 scripts/compile_state_books.py --book-type study_guide --passes 3
"""

import argparse
import os
import re
import shutil
import subprocess
import sys
import time
from concurrent.futures import ThreadPoolExecutor, as_completed
from datetime import date
from pathlib import Path
from typing import List, Optional, Tuple

# -- Imports from centralised config --
from config import (
    ALL_BOOK_TYPES,
    BOOK_TYPES,
    MAX_WORKERS,
    NON_PREVIEW_KEYS,
    XELATEX_PASSES,
    PREVIEW_KEYS,
    TEXLIVE_YEAR,
    find_workspace,
    prompt_book_type,
    prompt_states,
    tex_filename,
)
from config_loader import load_config


# ============================================================================
# COMPILATION PHASE
# ============================================================================

class LatexCompilationError(Exception):
    pass


def _has_fatal_latex_error(output: str) -> bool:
    """Detect fatal LaTeX errors in xelatex output.

    xelatex may return non-zero for non-fatal reasons (e.g. "rerun" warnings).
    We only treat clearly fatal conditions as hard failures.
    """
    fatal_markers = [
        "! Emergency stop.",
        "Fatal error occurred",
        "No output PDF file produced",
        "!  ==> Fatal error occurred",
    ]
    return any(marker in output for marker in fatal_markers)


def _pdf_page_count(pdf_path: Path, latex_output: str = "") -> Optional[int]:
    """Extract page count from the last xelatex run or via pdfinfo.

    Strategy:
      1. Parse 'Output written on ... (N pages' from xelatex stdout.
      2. Fall back to the ``pdfinfo`` CLI tool (from poppler).
    """
    # 1) Parse LaTeX output
    if latex_output:
        m = re.search(r'Output written on.*?\((\d+)\s+pages?', latex_output, re.DOTALL)
        if m:
            return int(m.group(1))

    # 2) Fall back to pdfinfo
    try:
        result = subprocess.run(
            ["pdfinfo", str(pdf_path)],
            capture_output=True, text=True, timeout=10,
        )
        if result.returncode == 0:
            m = re.search(r'^Pages:\s+(\d+)', result.stdout, re.MULTILINE)
            if m:
                return int(m.group(1))
    except (FileNotFoundError, subprocess.TimeoutExpired):
        pass

    return None


def _tail_words(text: str, max_words: int = 200) -> str:
    words = text.split()
    return " ".join(words[-max_words:])


def _final_output_pdf_filename(book_type: str, state_slug: str) -> str:
    """Return final PDF filename for final_output folders.

    Non-preview books: <state>_<YYYY-MM-DD>.pdf
    Preview books:     <state>_preview_<YYYY-MM-DD>.pdf
    """
    today = date.today().isoformat()
    if book_type.startswith("preview_"):
        return f"{state_slug}_preview_{today}.pdf"
    return f"{state_slug}_{today}.pdf"


def _texmfcnf_env() -> dict:
    """Return an environment dict with TEXMFCNF set for increased TeX memory.

    TeX Live's default main_memory (5 000 000 words) is too small for
    state books that include many TikZ-heavy additional topics.  A user-
    level texmf.cnf at ~/Library/texmf/web2c/texmf.cnf (macOS) or
    ~/texmf/web2c/texmf.cnf (Linux) should contain main_memory = 12000000.
    After creating it, rebuild the format once with:

        TEXMFCNF="$HOME/Library/texmf/web2c:..." fmtutil-user --byfmt xelatex

    This function prepends the user texmf path so xelatex picks up the
    increased memory limit.
    """
    home = Path.home()
    user_web2c_dirs = [
        str(home / "Library" / "texmf" / "web2c"),
        str(home / "texmf" / "web2c"),
    ]
    system_dirs = [
        f"/usr/local/texlive/{TEXLIVE_YEAR}",
        f"/usr/local/texlive/{TEXLIVE_YEAR}/texmf-dist/web2c",
    ]
    env = os.environ.copy()
    env["TEXMFCNF"] = ":".join(user_web2c_dirs + system_dirs)
    return env


def compile_single_book(
    tex_path: Path,
    workspace: Path,
    passes: int = 2,
) -> Tuple[str, bool, str]:
    """Compile a single .tex file using xelatex (multiple passes).

    Returns (job_name, success, message).
    """
    state_slug = tex_path.parent.name
    job_name = tex_path.stem
    rel_tex = tex_path.relative_to(workspace)

    print(f"  > Compiling: {rel_tex}")

    build_dir = workspace / "build" / job_name
    build_dir.mkdir(parents=True, exist_ok=True)
    rel_build = build_dir.relative_to(workspace)

    cmd = [
        "xelatex",
        "-interaction=nonstopmode",
        f"-output-directory={rel_build}",
        str(rel_tex),
    ]

    env = _texmfcnf_env()
    last_output = ""

    for pass_num in range(1, passes + 1):
        try:
            result = subprocess.run(
                cmd,
                cwd=str(workspace),
                stdout=subprocess.PIPE,
                stderr=subprocess.PIPE,
                text=True,
                errors="replace",
                env=env,
            )

            combined_output = (result.stdout or "") + "\n" + (result.stderr or "")
            last_output = combined_output
            if result.returncode != 0 and _has_fatal_latex_error(combined_output):
                last_200 = _tail_words(combined_output, max_words=200)
                return (
                    job_name,
                    False,
                    f"LaTeX failed on pass {pass_num}/{passes} for {job_name}\n{last_200}",
                )
        except subprocess.TimeoutExpired:
            return (job_name, False, f"Pass {pass_num} timed out")

    pdf_path = build_dir / f"{job_name}.pdf"
    if not pdf_path.exists():
        return (job_name, False, "PDF not found after compilation")

    pages = _pdf_page_count(pdf_path, last_output)
    if pages is not None and pages == 0:
        return (job_name, False, f"PDF produced but has 0 pages: {pdf_path.relative_to(workspace)}")

    # Copy PDF to final_output/ immediately
    dst_rel: Optional[str] = None
    book_type = job_name.rsplit(f"_{state_slug}", 1)[0]
    bt_cfg = ALL_BOOK_TYPES.get(book_type)
    if bt_cfg:
        output_dir = workspace / "final_output" / bt_cfg["output_subdir"]
        output_dir.mkdir(parents=True, exist_ok=True)
        dst = output_dir / _final_output_pdf_filename(book_type, state_slug)
        shutil.copy2(pdf_path, dst)
        dst_rel = str(dst.relative_to(workspace))

    pdf_rel = str(pdf_path.relative_to(workspace))
    pages_str = f" ({pages} pages)" if pages is not None else ""
    if dst_rel:
        info = f"\u2705 {dst_rel}{pages_str}"
    else:
        info = f"\u2705 {pdf_rel}{pages_str}"
    return (job_name, True, info)


def compile_books_concurrent(
    tex_paths: List[Path],
    workspace: Path,
    max_workers: int,
    passes: int = 2,
) -> Tuple[List[str], List[str]]:
    """Compile all .tex files concurrently in a single thread pool.

    Returns (succeeded_jobs, failed_messages).
    """
    succeeded: List[str] = []
    failed: List[str] = []
    total = len(tex_paths)

    with ThreadPoolExecutor(max_workers=max_workers) as pool:
        futures = {
            pool.submit(compile_single_book, tp, workspace, passes): tp
            for tp in tex_paths
        }
        done_count = 0
        for future in as_completed(futures):
            done_count += 1
            tex_path = futures[future]
            try:
                job_name, ok, msg = future.result()
            except Exception as exc:
                job_name = tex_path.stem
                ok = False
                msg = str(exc)

            if ok:
                succeeded.append(job_name)
                print(f"  [{done_count}/{total}] OK {job_name}")
                print(f"                  {msg}")
            else:
                failed.append(msg)
                print(f"  [{done_count}/{total}] FAIL {job_name}")

    return succeeded, failed


# ============================================================================
# CLI
# ============================================================================

def parse_args() -> argparse.Namespace:
    _help_workers = f"Max concurrent xelatex processes (default: {MAX_WORKERS}, override with MAX_WORKERS in .env)"
    _help_passes = f"Number of xelatex passes per book (default: {XELATEX_PASSES}, override with XELATEX_PASSES in .env)"

    parser = argparse.ArgumentParser(
        description="Compile state-specific Grade 4 math LaTeX books and collect PDFs.",
        formatter_class=argparse.RawDescriptionHelpFormatter,
        epilog=(
            "examples:\n"
            "  compile_state_books.py --book-type all_in_one                     # all 50 states\n"
            "  compile_state_books.py --book-type study_guide                    # all 50 states (brief)\n"
            "  compile_state_books.py --book-type all --states texas             # all book types, one state (concurrent!)\n"
            "  compile_state_books.py --book-type all_in_one --states texas,florida\n"
            "  compile_state_books.py --book-type study_guide --jobs 8\n"
            "  compile_state_books.py --book-type all_in_one --passes 3\n"
        ),
    )
    parser.add_argument(
        "--workspace",
        type=Path,
        default=None,
        help="Workspace root directory (auto-detected if omitted)",
    )
    _all_choices = list(ALL_BOOK_TYPES.keys()) + ["all", "all_previews"]
    parser.add_argument(
        "--book-type",
        choices=_all_choices,
        default=None,
        help="Book type to compile. Use 'all' for every non-preview type, 'all_previews' for all preview variants. (interactive if omitted)",
    )
    parser.add_argument(
        "--states",
        type=str,
        default=None,
        help="Comma-separated state slugs to compile (default: all 50)",
    )
    parser.add_argument(
        "--jobs", "-j",
        type=int,
        default=None,
        help=_help_workers,
    )
    parser.add_argument(
        "--passes",
        type=int,
        default=None,
        help=_help_passes,
    )
    return parser.parse_args()


# ============================================================================
# MAIN
# ============================================================================

def main() -> None:
    args = parse_args()

    workspace = (args.workspace or find_workspace()).resolve()
    print(f"Workspace: {workspace}")

    config = load_config(workspace)
    all_state_slugs = config.all_state_slugs

    # ── Interactive prompts when arguments are omitted ──────────────────
    book_type = args.book_type
    if book_type is None:
        book_type = prompt_book_type(
            list(BOOK_TYPES.keys()),
            allow_all=True,
            allow_all_previews=True,
        )

    if book_type == "all":
        bt_keys = NON_PREVIEW_KEYS
    elif book_type == "all_previews":
        bt_keys = PREVIEW_KEYS
    else:
        bt_keys = [book_type]

    if args.states:
        requested = [s.strip().lower() for s in args.states.split(",")]
        unknown = [s for s in requested if s not in all_state_slugs]
        if unknown:
            print(f"ERROR: Unknown state(s): {', '.join(unknown)}")
            print(f"  Valid slugs: {', '.join(sorted(all_state_slugs))}")
            sys.exit(1)
        state_slugs = requested
    else:
        states_input = prompt_states(all_state_slugs)
        if states_input is None:
            state_slugs = all_state_slugs
        else:
            state_slugs = [s.strip().lower() for s in states_input.split(",")]

    # -- Discover ALL .tex files across every requested book type --
    all_tex_paths: List[Path] = []
    for bt_key in bt_keys:
        found = 0
        for slug in state_slugs:
            p = workspace / "state_books" / slug / tex_filename(bt_key, slug)
            if p.exists():
                all_tex_paths.append(p)
                found += 1
        if found == 0:
            print(f"  Warning: No .tex files for {bt_key}")

    if not all_tex_paths:
        print("ERROR: No .tex files found. Run generate scripts first.")
        sys.exit(1)

    max_workers = args.jobs or MAX_WORKERS
    passes = args.passes or XELATEX_PASSES

    # -- Compile everything in ONE concurrent batch --
    print(f"\nCompiling {len(all_tex_paths)} books across {len(bt_keys)} type(s)")
    print(f"   Workers: {max_workers}  |  Passes: {passes}  |  States: {len(state_slugs)}")
    print()

    t0 = time.monotonic()
    succeeded, failed = compile_books_concurrent(
        all_tex_paths, workspace, max_workers, passes,
    )
    elapsed = time.monotonic() - t0

    sep = "=" * 60
    print(f"\n{sep}")
    print(f"Succeeded: {len(succeeded)}  |  Failed: {len(failed)}  |  Time: {elapsed:.1f}s")

    if failed:
        print("\nFailed compilations:")
        for msg in failed:
            print(f"   {msg[:200]}")
        sys.exit(1)


if __name__ == "__main__":
    main()
