#!/usr/bin/env python3
"""
Compile preview PDFs for all (or selected) Grade 7 book types.

This is a focused companion to compile_state_books.py that deals exclusively
with preview variants.  It discovers preview .tex files already generated by
generate_state_books.py under state_books/<state>/ and compiles them
concurrently with xelatex.

Preview .tex files are named:  preview_<book_type>_<state>-grade7.tex
Final PDFs land in:            final_output/<output_subdir>/<state>_preview_<date>.pdf

Usage examples:
    # Compile ALL preview types for every state
    python3 scripts/compile_preview_books.py

    # All previews for a single state
    python3 scripts/compile_preview_books.py --states texas

    # All previews for multiple states
    python3 scripts/compile_preview_books.py --states texas,florida,california

    # Only one preview book type
    python3 scripts/compile_preview_books.py --book-type all_in_one

    # Control concurrency (or set MAX_WORKERS in .env)
    python3 scripts/compile_preview_books.py --jobs 4

    # Extra xelatex passes (or set XELATEX_PASSES in .env)
    python3 scripts/compile_preview_books.py --passes 3
"""

import argparse
import sys
import time
from pathlib import Path
from typing import List

from compile_state_books import compile_books_concurrent
from config import (
    ALL_BOOK_TYPES,
    BOOK_TYPES,
    MAX_WORKERS,
    NON_PREVIEW_KEYS,
    PREVIEW_BOOK_TYPES,
    PREVIEW_KEYS,
    XELATEX_PASSES,
    find_workspace,
    prompt_book_type,
    prompt_states,
    tex_filename,
)
from config_loader import load_config


# ============================================================================
# CLI
# ============================================================================

def parse_args() -> argparse.Namespace:
    _help_bt = (
        "Preview book type to compile. "
        "Use a bare key like 'all_in_one' (the 'preview_' prefix is added for you) "
        "or the full 'preview_all_in_one' key.  "
        "Omit for all preview types."
    )
    _help_workers = (
        f"Max concurrent xelatex processes "
        f"(default: {MAX_WORKERS}, override with MAX_WORKERS in .env)"
    )
    _help_passes = (
        f"Number of xelatex passes per book "
        f"(default: {XELATEX_PASSES}, override with XELATEX_PASSES in .env)"
    )

    parser = argparse.ArgumentParser(
        description="Compile Grade 7 preview PDFs for all or selected book types.",
        formatter_class=argparse.RawDescriptionHelpFormatter,
        epilog=(
            "examples:\n"
            "  compile_preview_books.py                            # all previews, all states\n"
            "  compile_preview_books.py --states texas             # all previews, one state\n"
            "  compile_preview_books.py --book-type all_in_one     # one type, all states\n"
            "  compile_preview_books.py --book-type all_in_one --states texas,florida\n"
            "  compile_preview_books.py --jobs 8\n"
        ),
    )
    parser.add_argument(
        "--workspace",
        type=Path,
        default=None,
        help="Workspace root directory (auto-detected if omitted)",
    )
    # Accept bare keys ("all_in_one") or full preview keys ("preview_all_in_one")
    _bt_choices = NON_PREVIEW_KEYS + PREVIEW_KEYS
    parser.add_argument(
        "--book-type",
        choices=_bt_choices,
        default=None,
        metavar="BOOK_TYPE",
        help=_help_bt,
    )
    parser.add_argument(
        "--states",
        type=str,
        default=None,
        help="Comma-separated state slugs (default: all 50 states)",
    )
    parser.add_argument(
        "--jobs", "-j",
        type=int,
        default=None,
        help=_help_workers,
    )
    parser.add_argument(
        "--passes",
        type=int,
        default=None,
        help=_help_passes,
    )
    return parser.parse_args()


# ============================================================================
# MAIN
# ============================================================================

def main() -> None:
    args = parse_args()

    workspace = (args.workspace or find_workspace()).resolve()
    print(f"Workspace: {workspace}")

    config = load_config(workspace)
    all_state_slugs = config.all_state_slugs

    # -- Resolve which preview keys to compile --
    book_type_arg = args.book_type
    if book_type_arg is None:
        # Interactive prompt — show bare keys (without "preview_" prefix) for readability
        bare_keys = [k.removeprefix("preview_") for k in PREVIEW_KEYS]
        descriptions = {
            k.removeprefix("preview_"): v.get("description", "")
            for k, v in PREVIEW_BOOK_TYPES.items()
        }
        selected = prompt_book_type(
            bare_keys,
            descriptions=descriptions,
            allow_all=True,
            allow_all_previews=False,
        )
        if selected == "all":
            preview_keys = PREVIEW_KEYS
        else:
            preview_keys = [f"preview_{selected}"]
    elif book_type_arg.startswith("preview_"):
        preview_keys = [book_type_arg]
    else:
        # Bare key — prepend "preview_"
        full_key = f"preview_{book_type_arg}"
        if full_key not in ALL_BOOK_TYPES:
            print(f"ERROR: No preview variant found for '{book_type_arg}'")
            print(f"  Available: {', '.join(NON_PREVIEW_KEYS)}")
            sys.exit(1)
        preview_keys = [full_key]

    # -- Resolve which states to compile --
    if args.states:
        requested = [s.strip().lower() for s in args.states.split(",")]
        unknown = [s for s in requested if s not in all_state_slugs]
        if unknown:
            print(f"ERROR: Unknown state(s): {', '.join(unknown)}")
            print(f"  Valid slugs: {', '.join(sorted(all_state_slugs))}")
            sys.exit(1)
        state_slugs = requested
    else:
        states_input = prompt_states(all_state_slugs)
        if states_input is None:
            state_slugs = all_state_slugs
        else:
            state_slugs = [s.strip().lower() for s in states_input.split(",")]

    # -- Discover preview .tex files --
    # Preview .tex files are named  preview_<book_type>_<state>-grade7.tex
    # which matches tex_filename("preview_<book_type>", state_slug).
    all_tex_paths = []
    for pk in preview_keys:
        found = 0
        for slug in state_slugs:
            p = workspace / "state_books" / slug / tex_filename(pk, slug)
            if p.exists():
                all_tex_paths.append(p)
                found += 1
        if found == 0:
            print(f"  Warning: No .tex files found for {pk} — run generate_state_books.py first")

    if not all_tex_paths:
        print("ERROR: No preview .tex files found. Run generate_state_books.py first.")
        sys.exit(1)

    max_workers = args.jobs or MAX_WORKERS
    passes = args.passes or XELATEX_PASSES

    print(
        f"\nCompiling {len(all_tex_paths)} preview book(s) across "
        f"{len(preview_keys)} type(s), {len(state_slugs)} state(s)"
    )
    print(f"   Workers: {max_workers}  |  Passes: {passes}")
    print()

    t0 = time.monotonic()
    succeeded, failed = compile_books_concurrent(
        all_tex_paths, workspace, max_workers, passes,
    )
    elapsed = time.monotonic() - t0

    sep = "=" * 60
    print(f"\n{sep}")
    print(
        f"Succeeded: {len(succeeded)}  |  Failed: {len(failed)}  |  Time: {elapsed:.1f}s"
    )

    if failed:
        print("\nFailed compilations:")
        for msg in failed:
            print(f"   {msg[:200]}")
        sys.exit(1)


if __name__ == "__main__":
    main()
